1
25
50
75
100
125
150
175
200
225
250
275
300
325
350
375
400
425
450
475
500
525
550
575
600
625
650
675
700
725
750
775
800
825
850
875
900
925
950
975
1000
elapsed:  7028.6  seconds
1025
1050
1075
1100
1125
1150
1175
1200
1225
1250
1275
1300
1325
1350
1375
1400
1425
1450
1475
1500
1525
1550
1575
1600
1625
1650
1675
1700
1725
1750
1775
1800
1825
1850
1875
1900
1925
1950
1975
2000
elapsed:  14092.2  seconds
2025
2050
2075
2100
2125
2150
2175
2200
2225
2250
2275
2300
2325
2350
2375
2400
2425
2450
2475
2500
2525
2550
2575
2600
2625
2650
2675
2700
2725
2750
2775
2800
2825
2850
2875
2900
2925
2950
2975
3000
elapsed:  21135.0  seconds
3025
3050
3075
3100
3125
3150
3175
3200
3225
3250
3275
3300
3325
3350
3375
3400
3425
3450
3475
3500
3525
3550
3575
3600
3625
3650
3675
3700
3725
3750
3775
3800
3825
3850
3875
3900
3925
3950
3975
4000
elapsed:  28168.0  seconds
4025
4050
4075
4100
4125
4150
4175
4200
4225
4250
4275
4300
4325
4350
4375
4400
4425
4450
4475
4500
4525
4550
4575
4600
4625
4650
4675
4700
4725
4750
4775
4800
4825
4850
4875
4900
4925
4950
4975
5000
elapsed:  35205.9  seconds
5025
5050
5075
5100
5125
5150
5175
5200
5225
5250
5275
5300
5325
5350
5375
5400
5425
5450
5475
5500
5525
5550
5575
5600
5625
5650
5675
5700
5725
5750
5775
5800
5825
5850
5875
5900
5925
5950
5975
6000
elapsed:  42257.5  seconds
6025
6050
6075
6100
6125
6150
6175
6200
6225
6250
6275
6300
6325
6350
6375
6400
6425
6450
6475
6500
6525
6550
6575
6600
6625
6650
6675
6700
6725
6750
6775
6800
6825
6850
6875
6900
6925
6950
6975
7000
elapsed:  49291.6  seconds
7025
7050
7075
7100
7125
7150
7175
7200
7225
7250
7275
7300
7325
7350
7375
7400
7425
7450
7475
7500
7525
7550
7575
7600
7625
7650
7675
7700
7725
7750
7775
7800
7825
7850
7875
7900
7925
7950
7975
8000
elapsed:  56330.6  seconds
8025
8050
8075
8100
8125
8150
8175
8200
8225
8250
8275
8300
8325
8350
8375
8400
8425
8450
8475
8500
8525
8550
8575
8600
8625
8650
8675
8700
8725
8750
8775
8800
8825
8850
8875
8900
8925
8950
8975
9000
elapsed:  63355.0  seconds
9025
9050
9075
9100
9125
9150
9175
9200
9225
9250
9275
9300
9325
9350
9375
9400
9425
9450
9475
9500
9525
9550
9575
9600
9625
9650
9675
9700
9725
9750
9775
9800
9825
9850
9875
9900
9925
9950
9975
elapsed:  70399.5  seconds
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
total time:  70407.0  seconds
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
true R:  [[1.99256680e-01 2.58586950e-01 1.17521383e+01 2.06417034e-01
  3.64065773e+00 6.17997717e-01 6.27255552e+00 4.95339962e-01
  2.64044770e-01 4.00507789e+00 4.01348949e-01 7.69204556e-01
  6.99152509e+00 6.79055353e-01 1.70457570e+00 1.69646024e+00
  2.24816240e+01 7.13374331e-01 1.14774455e+00 7.51261104e+00
  1.57355215e+01 5.36760295e+00 4.50684688e+01 1.91635525e+00
  1.20640099e+01 3.37968914e-01 5.09776468e-01 1.46663319e-01
  4.23815237e+00 2.86726558e+00 6.45128204e-01 3.91297438e+01]
 [5.14385598e+01 1.51715646e-01 5.97298916e-01 2.67920863e-01
  1.96138348e+02 9.57637842e-01 4.17135162e-01 5.71527526e+02
  2.85183790e-01 9.95457887e+00 1.46250011e+00 5.23648281e-01
  9.41344522e-01 2.02872540e+00 2.55152862e-01 2.41184654e+00
  3.51986204e-01 5.13367145e+00 4.90933581e+00 3.75291030e-01
  6.52733808e-01 2.49550421e+00 4.92694151e+01 1.59418683e+00
  1.39635506e+01 3.59062180e+00 2.35639330e-01 7.53026570e-01
  7.65649816e-01 1.07164698e+00 2.58115286e-01 1.98264820e+01]]
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
MCMC_test.py:418: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.subplots()
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: overflow encountered in func (vectorized)
  outputs = ufunc(*inputs)
/data/accounts/shi/.conda/envs/emulator4/lib/python3.8/site-packages/numpy/lib/function_base.py:2387: RuntimeWarning: invalid value encountered in func (vectorized)
  outputs = ufunc(*inputs)
